import "../styles/globals.css";
import type { AppProps } from "next/app";
import { TodoProvider } from "@context/todoProvider";
import { ReactElement, ReactNode } from "react";
import { NextPage } from "next";
import Head from "next/head";

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function MyApp({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => <>{page}</>);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoProvider>{getLayout(<Component {...pageProps} />)}</TodoProvider>
    </>
  );
}

export default MyApp;
