import "../styles/globals.css";
import type { AppProps } from "next/app";

import { ReactElement, ReactNode } from "react";
import { NextPage } from "next";
import Head from "next/head";
import { Quicksand } from "@next/font/google";
import Theme from "@styles/Theme";

const quitcksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function MyApp({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => <>{page}</>);

  return (
    <>
      <Head>
        <title>Kiosko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Theme>
        <div className={quitcksand.className} style={{ minHeight: "100vh" }}>
          {getLayout(<Component {...pageProps} />)}
        </div>
      </Theme>
    </>
  );
}

export default MyApp;
